name: url_filter_nilaya_lambda
on:
  push:
    branches:
      - newsletter_url_filter_nilaya
    paths:
      - 'url_etc_lambda_nilaya/**'
      - '.github/workflows/url_filter_nilaya_lambda.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: qxf2/py-lambda-action@v1.0.2
      with:
        lambda_directory: 'url_etc_lambda_nilaya'
        lambda_function_name: 'arn:aws:lambda:ap-south-1:285993504765:function:Url_Filtering_Nilaya_lambda'
        lambda_layer_arn: 'arn:aws:lambda:ap-south-1:285993504765:layer:nilaya_layer:1'
        requirements_txt: 'url_etc_lambda_nilaya/requirements.txt'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SKYPE_SENDER_REGION }}