name: work-anniversary-reminder
on:
  push:
    branches:
      - work-anniversary
    paths:
      - 'work-anniversary/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy code to Lambda
      uses: qxf2/py-lambda-action@v1.0.2
      with:
        lambda_directory: 'work-anniversary'
        lambda_function_name: 'arn:aws:lambda:ap-south-1:285993504765:function:work-anniversary'
        lambda_layer_arn: 'arn:aws:lambda:ap-south-1:285993504765:layer:employee-work-anniversary'
        requirements_txt: 'work-anniversary/requirements.txt'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SKYPE_SENDER_REGION }}